name: a_vault
description: A secure photo & video vault with biometric + PIN lock.
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies: # بلوك واحد بس
  flutter:
    sdk: flutter
  local_auth: ^2.1.7
  flutter_secure_storage: ^9.0.0
  encrypt: ^5.0.1
  image_picker: ^1.0.7
  path_provider: ^2.1.3
  crypto: ^3.0.3
  flutter_launcher_icons: ^0.13.1 # ضيف المكتبة هنا مع الباقي

flutter: # بلوك واحد بس
  uses-material-design: true

flutter_icons: # ده في آخر الملف خالص
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21
